//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedBookDRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programari_Pacienti
    {
        public int IdProgramare { get; set; }
        public int IdSpecializare { get; set; }
        public int IdPacient { get; set; }
        public int IdDoctor { get; set; }
        public System.DateTime DataProgramare { get; set; }
        public System.TimeSpan OraProgramare { get; set; }
        public string Descriere { get; set; }
        public Nullable<double> PretTotal { get; set; }
    
        public virtual Doctori Doctori { get; set; }
        public virtual Pacienti Pacienti { get; set; }
        public virtual Specializari Specializari { get; set; }
    }
}
