//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedBookDRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiciiMedicale
    {
        public int IdServiciu { get; set; }
        public string Denumire { get; set; }
        public double Pret { get; set; }
    }
}
