//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedBookDRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specializari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specializari()
        {
            this.Programari_Pacienti = new HashSet<Programari_Pacienti>();
            this.SpecializariDoctoris = new HashSet<SpecializariDoctori>();
        }
    
        public int IdSpecializare { get; set; }
        public string Denumire { get; set; }
        public string Studii { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programari_Pacienti> Programari_Pacienti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecializariDoctori> SpecializariDoctoris { get; set; }
    }
}
